#!/bin/bash

:<<EOF
  1. copy .vim and .vimrc to your ~
  2. clone vundle
  3. install bundle
EOF

cmds=(
  "cp -r `pwd`/.vim `pwd`/.vimrc $HOME"
  "git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle"
  "vim +BundleInstall +qall"
)

execIt(){
  echo "################################### STEP $2 ###################################"
  echo "$1"
  $1
}

for i in "${!cmds[@]}"
do
  execIt "${cmds[$i]}" $i
done
